name: smart_spacing
description: A Flutter package for consistent, semantic spacing (padding, margin, spacer).
version: 0.0.1
homepage: https://github.com/mohammadtaghipour/smart_spacing
repository: https://github.com/mohammadtaghipour/smart_spacing

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  